@startuml

package "People" {
  folder "Domain" {
    database PersonRepository
    database PersonAuditTrailRepository
  }
  folder "Services" {
    component PersonRegistrationService
    component PersonUpdatingService
  }
}

@enduml