@startuml

!pragma useVerticalIf on
skinparam nodesep 80
skinparam ranksep 80

package "People" {
  database PersonRepository
  database PersonAuditTrailRepository
  interface PersonRegistrationService
  interface PersonUpdatingService
  component PersonRegistrationServiceImpl
  component PersonUpdatingServiceImpl

  PersonRegistrationServiceImpl ..> PersonRegistrationService
  PersonUpdatingServiceImpl ..> PersonUpdatingService

  PersonRegistrationService ..> PersonRepository
  PersonUpdatingServiceImpl ..> PersonRepository
  PersonUpdatingServiceImpl ..> PersonAuditTrailRepository
}

package "Customers" {
  database CustomerRepository
  database CustomerAuditTrailRepository
  interface CustomerRegistrationService
  interface CustomerUpdatingService
  interface CustomerRetrievalService
  component CustomeRegistrationServiceImpl
  component CustomerUpdatingServiceImpl
  component CustomerRetrievalServiceImpl

  CustomeRegistrationServiceImpl..> CustomerRegistrationService
  CustomerUpdatingServiceImpl ..> CustomerUpdatingService
  CustomerRetrievalServiceImpl ..> CustomerRetrievalService

  CustomerRegistrationService ..> CustomerRepository
  CustomerUpdatingServiceImpl ..> CustomerRepository
  CustomerUpdatingServiceImpl ..> CustomerAuditTrailRepository
  CustomerRetrievalServiceImpl ..> CustomerRepository
}

PersonRegistrationService <.. CustomerRegistrationService

@enduml