@startuml component_diagram

left to right direction

package "Person Module" {
    [Person Registration Context]
    [Person Update Context]
}

package "Customer Module" {
    [Customer Registration Context]
    [Customer Update Context]
    [Customer Retrieval Context]
}

package "Doctor Module" {
    [Doctor Registration Context]
    [Doctor Management Context]
    [Doctor Retrieval Context]
}

package "Nurse Module" {
    [Nurse Registration Context]
    [Nurse Managemen tContext]
    [Nurse Retrieval Context]
}

package "Medical Slot Module" {
    [Slot Registration Context]
    [Slot Management Context]
    [Slot Retrieval Context]
}

package "Medical Appointment Module" {
    [Appointment Registration Context]
    [Appointment Management Context]
    [Appointment Retrieval Context]
}

@enduml
