@startuml

skinparam defaultFontSize 50

participant "Client"
participant "PersonRegistrationDTO" as registrationDTO
participant "PersonRegistrationService" as registrationService
participant "Customer" as entity
participant "Repository" as repository
participant "ResponseDTO" as responseDTO
participant "ResponseEntity"

Client -> ResponseEntity: HTTP 1.1 POST /api/v2/customers (with registrationDTO)

registrationDTO -> registrationService: transfer validated input

alt SSN and email are unique

registrationService -> entity: create Person

registrationService -> entity: save(Person)

entity <-- repository: save(Customer)

entity -> responseDTO: toDTO(Customer)

responseDTO -> ResponseEntity: wrapWith201(DTO)

Client <-- ResponseEntity: HTTP 1.1 201 CREATED + CustomerResponseDTO

else SSN is duplicated

registrationService <-- repository: SSN is duplicated

registrationService -> ResponseEntity: wrapWith409(DTO)

Client <-- ResponseEntity: HTTP 1.1 409 CONFLICT

else email is duplicated

registrationService <-- repository: email is duplicated

registrationService -> ResponseEntity: wrapWith409(DTO)

Client <-- ResponseEntity: HTTP 1.1 409 CONFLICT

end

@enduml
