@startuml

skinparam defaultFontSize 60

participant "Client"
participant "Input" as input
participant "DoctorFinder" as finder
participant "Doctor" as entity
participant "Repository" as repository
participant "ResponseEntity"

Client -> ResponseEntity: HTTP 1.1 PATCH /api/v2/doctors/{license_number}/{state}/rehiring

alt doctor is active

input -> finder: findByMedicalLicenseNumber(license_number, state)

finder -> entity: doctor retrieved

entity -> repository: markAsRehired(doctor)

entity <-- repository: save(doctor)

repository -> ResponseEntity: wrapWith204(doctor)

Client <-- ResponseEntity: HTTP 1.1 204 NOT CONTENT

else doctor not found

finder <-- ResponseEntity: wrapWith404(doctor)

Client <-- ResponseEntity: HTTP 1.1 404 NOT FOUND

else doctor is active

finder <-- ResponseEntity: wrapWith409(doctor)

Client <-- ResponseEntity: HTTP 1.1 409 CONFLICT

end

@enduml
