@startuml

skinparam defaultFontSize 58

participant "Client"
participant "PersonRegistrationDTO" as registrationDTO
participant "PersonRegistrationService" as registrationService
participant "Doctor" as entity
participant "Repository" as repository
participant "ResponseDTO" as responseDTO
participant "ResponseEntity"

Client -> ResponseEntity: HTTP 1.1 POST /api/v2/doctors (with registrationDTO)

registrationDTO -> registrationService: transfer validated input

alt SSN and email and medical license number are unique

registrationService -> entity: create Person

registrationService -> entity: save(Person)

entity <-- repository: save(Doctor)

entity -> responseDTO: toDTO(Doctor)

responseDTO -> ResponseEntity: wrapWith201(DTO)

Client <-- ResponseEntity: HTTP 1.1 201 CREATED + DoctorResponseDTO

else SSN is duplicated

registrationService <-- repository: SSN is duplicated

registrationService -> ResponseEntity: wrapWith409(DTO)

Client <-- ResponseEntity: HTTP 1.1 409 CONFLICT + DoctorResponseDTO

else email is duplicated

registrationService <-- repository: email is duplicated

registrationService -> ResponseEntity: wrapWith409(DTO)

Client <-- ResponseEntity: HTTP 1.1 409 CONFLICT

else medical license number is duplicated

registrationService <-- repository: medical license number is duplicated

registrationService -> ResponseEntity: wrapWith409(DTO)

Client <-- ResponseEntity: HTTP 1.1 409 CONFLICT

end

@enduml
