@startuml

entity "Person" {
 +id: String
 +firstName: String
 +middleName: String?
 +lastName: String
 +ssn: String
 +birthDate: LocalDate
 +phoneNumber: String
 +gender: Gender
 +email: String
 +createdAt: LocalDateTime
 +updatedAt: LocalDateTime
 
 +of(registratitionDTO: PersonRegistrationDTO): Person
 +update(updatingDTO: PersonUpdatingDTO)
}

entity "Customer" {
 +id: String
 +address: Address
 +person: Person
 +createdAt: LocalDateTime
 +updatedAt: LocalDateTime
 
 +of(person: Person, address: Address): Customer
 +toDTO(): CustomerResponseDTO
}

entity "Doctor" {
 +id: String
 +medicalLicenseNumber: MedicalLicenseNumber
 +status: ProfessionalStatus
 +person: Person
 +createdAt: LocalDateTime
 +updatedAt: LocalDateTime
 +terminatedAt: LocalDateTime
 
 +of(person: Person, medicalLicenseNumber: MedicalLicenseNumber): Doctor
 +markAsTerminated()
 +markAsRehired()
 +toDTO(): DoctorResponseDTO
}

entity "MedicalSlot" {
  +id: String
  +doctor: Doctor
  +status: MedicalSlotStatus
  +availableAt: LocalDateTime
  +canceledAt: LocalDateTime?
  +completedAt: LocalDateTime?
  
  +of(doctor: Doctor, availableAt: LocalDateTime): MedicalSlot
  +markAsCanceled()
  +markAsCompleted()
  +toDTO(): MedicalSlotResponseDTO
}

entity "MedicalAppointment" {
  +id: String
  +doctor: Doctor
  +customer: Customer
  +status: MedicalAppointmentStatus
  +bookedAt: LocalDateTime
  +canceledAt: LocalDateTime?
  +completedAt: LocalDateTime?
  +price: BigDecimal?
  
  +of(doctor: Doctor, availableAt: LocalDateTime): MedicalSlot
  +markAsCanceled()
  +markAsCompleted()
  +markAsPaid()
  +toDTO(): MedicalAppointmentResponseDTO
}

Customer ||--|| Person
Doctor ||--|| Person
MedicalSlot }o--|| Doctor
MedicalAppointment }o--|| Doctor
MedicalAppointment }o--|| Customer
MedicalSlot ||--|| MedicalAppointment

@enduml