@startuml

skinparam defaultFontSize 60

participant "Client"
participant "Input"
participant "DoctorFinder" as finder
participant "MedicalSlot" as ms 
participant "Repository" as repository
participant "ResponseDTO" as responseDTO
participant "ResponseEntity"

Client -> ResponseEntity: HTTP 1.1 POST /api/v2/medical_slots/{license_number}/{state}/{available_at}

alt default behavior

Input -> finder: pass license_number as argument

Input -> finder: pass state as argument

finder -> finder: doctor retrieved

finder -> ms: provide the argument Doctor

Input -> ms: provide the argument available_at

ms -> repository: create MedicalSlot

ms <-- repository: save(MedicalSlot)

ms -> responseDTO: toDTO(MedicalSlot)

responseDTO -> ResponseEntity: wrapWith201(DTO)

Client <-- ResponseEntity: HTTP 1.1 201 CREATED + MedicalSlotRepository

else doctor was not found

finder -> ResponseEntity: wrapWith404(MedicalSlot)

Client <-- ResponseEntity: HTTP 1.1 404 NOT FOUND

else duplicated date and time

finder -> ResponseEntity: wrapWith409(MedicalSlot)

Client <-- ResponseEntity: HTTP 1.1 409 CONFLICT

end

@enduml
