@startuml

skinparam defaultFontSize 60

participant "Client"
participant "Input"
participant "CardFinder"
participant "MedicalAppointmentFinder"
participant "Payment"
participant "Repository"
participant "ResponseEntity"

alt default behavior

Client -> ResponseEntity: HTTP 1.1 POST /api/v2/payment/{card_id}/{medical_appointment_id}

Input -> CardFinder: pass card_id as argument

CardFinder -> CardFinder: return card

Input -> MedicalAppointmentFinder: pass medical_appointment_id as argument

MedicalAppointmentFinder -> MedicalAppointmentFinder: return medical appointment

CardFinder -> Payment: pass card as argument

MedicalAppointmentFinder -> Payment: pass medical appointment as argument

Payment -> Payment: create payment

Payment -> ResponseEntity: wrapWith201(Payment)

Client <-- ResponseEntity: HTTP 1.1 201 CREATED + MedicalSlotRepository

else medical appointment not found

MedicalAppointmentFinder -> ResponseEntity: wrapWith404(MedicalAppointment)

Client <-- ResponseEntity: HTTP 1.1 404 NOT FOUND

else card not found

CardFinder -> ResponseEntity: wrapWith404(MedicalAppointment)

Client <-- ResponseEntity: HTTP 1.1 404 NOT FOUND

else cancelled medical appointment

MedicalAppointmentFinder -> ResponseEntity: wrapWith409(MedicalAppointment)

Client <-- ResponseEntity: HTTP 1.1 409 CONFLICT

else active medical appointment

MedicalAppointmentFinder -> ResponseEntity: wrapWith409(MedicalAppointment)

Client <-- ResponseEntity: HTTP 1.1 409 CONFLICT

else paid medical appointment

MedicalAppointmentFinder -> ResponseEntity: wrapWith409(MedicalAppointment)

Client <-- ResponseEntity: HTTP 1.1 409 CONFLICT

end

@endunl